wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.16
    cli_version: 0.16.4
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1736990036.0
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 23
      4: 3.10.16
      5: 0.16.4
      8:
      - 1
      - 5
      13: darwin-x86_64
