wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.16
    cli_version: 0.16.4
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1737670455.0
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.10.16
      5: 0.16.4
      8:
      - 5
      13: darwin-x86_64
random_forest:
  desc: null
  value:
    n_estimators: 100
    criterion: gini
    max_depth: 5
    min_samples_split: 2
    min_samples_leaf: 1
    min_weight_fraction_leaf: 0.0
    max_features: null
    max_leaf_nodes: null
    min_impurity_decrease: 0.0
    bootstrap: true
    oob_score: false
    n_jobs: null
    random_state: null
    verbose: 0
    warm_start: false
    class_weight: null
    ccp_alpha: 0.0
    max_samples: null
tfidf:
  desc: null
  value:
    max_features: 100
features:
  desc: null
  value:
    numerical:
    - danceability
    - energy
    - loudness
    - speechiness
    - acousticness
    - instrumentalness
    - liveness
    - valence
    - tempo
    - duration_ms
    categorical:
    - time_signature
    - key
    nlp:
    - text_feature
export_artifact:
  desc: null
  value: model_export
