_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.8.20
            "5": 0.19.1
            "8":
                - 1
                - 5
            "12": 0.19.1
            "13": darwin-x86_64
