name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.2.3
  - pip=23.3.1
  - scikit-learn=1.4.1
  - matplotlib=3.8.3
  - plotly=5.19.0
  - pillow=10.2.0
  - pip:
      - wandb==0.16.4